In [25]:
import pandas as pd

marks = pd.Series([12,23,45,55])
print(marks)

0    12
1    23
2    45
3    55
dtype: int64

In [28]:

df = pd.read_csv("marks.txt")
print(df)

  Student   Math  Science  English  Computer  Social Studies  Total
0  Aarav     78    85       74       90        81...
1  Diya      88    79       92       87        84...
2  Ishaan    69    73       70       75        72...
3  Kavya     91    89       95       93        90...
4  Vivaan    76    80       78       82        77...
5  Anaya     84    86       88       85        87...
6  Aditya    72    68       75       70        74...
7  Meera     95    94       96       97        93...
8  Rohan     81    83       79       80        82...
9  Siya      87    90       85       88        91...

In [29]:
marks = pd.Series([12,56,78],index=['a' , 'b', 'c'])
print(marks)

a    12
b    56
c    78
dtype: int64

In [3]:
import pandas as pd
df = pd.read_csv("marks.txt")
print(df)
print(df.head())
print(df.tail())
print(df.shape)
print(df.columns)

print(df.index)
print(df.info())
print(df.describe())

  Student   Math  Science  English  Computer  Social Studies  Total
0  Aarav     78    85       74       90        81...
1  Diya      88    79       92       87        84...
2  Ishaan    69    73       70       75        72...
3  Kavya     91    89       95       93        90...
4  Vivaan    76    80       78       82        77...
5  Anaya     84    86       88       85        87...
6  Aditya    72    68       75       70        74...
7  Meera     95    94       96       97        93...
8  Rohan     81    83       79       80        82...
9  Siya      87    90       85       88        91...
  Student   Math  Science  English  Computer  Social Studies  Total
0  Aarav     78    85       74       90        81...
1  Diya      88    79       92       87        84...
2  Ishaan    69    73       70       75        72...
3  Kavya     91    89       95       93        90...
4  Vivaan    76    80       78       82        77...
  Student   Math  Science  English  Computer  Social Studies  Total
5  Anaya     84    86       88       85        87...
6  Aditya    72    68       75       70        74...
7  Meera     95    94       96       97        93...
8  Rohan     81    83       79       80        82...
9  Siya      87    90       85       88        91...
(10, 1)
Index(['Student   Math  Science  English  Computer  Social Studies  Total'], dtype='str')
RangeIndex(start=0, stop=10, step=1)
<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 1 columns):
 #   Column                                                             Non-Null Count  Dtype
---  ------                                                             --------------  -----
 0   Student   Math  Science  English  Computer  Social Studies  Total  10 non-null     str
dtypes: str(1)
memory usage: 112.0 bytes
None
       Student   Math  Science  English  Computer  Social Studies  Total
count                                                  10
unique                                                 10
top     Aarav     78    85       74       90        81...
freq                                                    1

In [11]:
df = pd.read_csv("new.txt")
print(df)
print(df.head())
print(df.tail())
print(df.shape)
print(df.columns)

print(df.index)
print(df.info())
print(df.describe())
print(df.iloc[0])

                                EmployeeID  Name Department  Salary
E101 Aarav Sharma    HR                                       45000
E102 Diya Verma      Finance                                  52000
E103 Vihaan Singh    IT                                       60000
E104 Ananya Gupta    Marketing                                48000
E105 Arjun Mehta     IT                                       65000
E106 Kavya Nair      HR                                       47000
E107 Rohan Kapoor    Finance                                  55000
E108 Meera Joshi     Marketing                                50000
E109 Aditya Rao      IT                                       72000
E110 Ishita Malhotra HR                                       46000
E111 Karan Patel     Finance                                  58000
E112 Sneha Iyer      Marketing                                51000
E113 Yash Chauhan    IT                                       69000
E114 Priya Desai     HR                                       49000
E115 Rahul Khanna    Finance                                  61000
E116 Neha Bansal     Marketing                                53000
E117 Manav Arora     IT                                       75000
E118 Riya Sethi      HR                                       50000
E119 Dev Agarwal     Finance                                  64000
E120 Simran Kaur     Marketing                                56000
                             EmployeeID  Name Department  Salary
E101 Aarav Sharma HR                                       45000
E102 Diya Verma   Finance                                  52000
E103 Vihaan Singh IT                                       60000
E104 Ananya Gupta Marketing                                48000
E105 Arjun Mehta  IT                                       65000
                            EmployeeID  Name Department  Salary
E116 Neha Bansal Marketing                                53000
E117 Manav Arora IT                                       75000
E118 Riya Sethi  HR                                       50000
E119 Dev Agarwal Finance                                  64000
E120 Simran Kaur Marketing                                56000
(20, 1)
Index(['   EmployeeID  Name Department  Salary'], dtype='str')
MultiIndex([('E101',    'Aarav Sharma',        'HR'),
            ('E102',      'Diya Verma',   'Finance'),
            ('E103',    'Vihaan Singh',        'IT'),
            ('E104',    'Ananya Gupta', 'Marketing'),
            ('E105',     'Arjun Mehta',        'IT'),
            ('E106',      'Kavya Nair',        'HR'),
            ('E107',    'Rohan Kapoor',   'Finance'),
            ('E108',     'Meera Joshi', 'Marketing'),
            ('E109',      'Aditya Rao',        'IT'),
            ('E110', 'Ishita Malhotra',        'HR'),
            ('E111',     'Karan Patel',   'Finance'),
            ('E112',      'Sneha Iyer', 'Marketing'),
            ('E113',    'Yash Chauhan',        'IT'),
            ('E114',     'Priya Desai',        'HR'),
            ('E115',    'Rahul Khanna',   'Finance'),
            ('E116',     'Neha Bansal', 'Marketing'),
            ('E117',     'Manav Arora',        'IT'),
            ('E118',      'Riya Sethi',        'HR'),
            ('E119',     'Dev Agarwal',   'Finance'),
            ('E120',     'Simran Kaur', 'Marketing')],
           )
<class 'pandas.DataFrame'>
MultiIndex: 20 entries, ('E101', 'Aarav Sharma', 'HR') to ('E120', 'Simran Kaur', 'Marketing')
Data columns (total 1 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0      EmployeeID  Name Department  Salary  20 non-null     int64
dtypes: int64(1)
memory usage: 420.0+ bytes
None
       EmployeeID  Name Department  Salary
count                            20.000000
mean                          56300.000000
std                            8921.293274
min                           45000.000000
25%                           49750.000000
50%                           54000.000000
75%                           61750.000000
max                           75000.000000
EmployeeID  Name Department  Salary    45000
Name: (E101, Aarav Sharma, HR), dtype: int64

In [3]:
import pandas as pd 
df = pd.read_csv("newdata.txt")
print(df)
#check null values
print(df.isnull())

   Employee_ID    Name Department   Salary  Experience
0          101    Aman         HR  45000.0         2.0
1          102   Priya         IT  55000.0         3.0
2          103   Rahul    Finance      NaN         4.0
3          104    Neha         IT  62000.0         NaN
4          105   Arjun        NaN  48000.0         2.0
5          106  Simran  Marketing  51000.0         3.0
6          107   Karan    Finance  59000.0         NaN
7          108     NaN         HR  47000.0         1.0
8          109   Meera  Marketing      NaN         5.0
9          110   Rohit         IT  65000.0         4.0
   Employee_ID   Name  Department  Salary  Experience
0        False  False       False   False       False
1        False  False       False   False       False
2        False  False       False    True       False
3        False  False       False   False        True
4        False  False        True   False       False
5        False  False       False   False       False
6        False  False       False   False        True
7        False   True       False   False       False
8        False  False       False    True       False
9        False  False       False   False       False

In [14]:
df = pd.read_csv("marks.txt", sep = r"\s+" , engine = "python")
df["Hindi"] = [50, 56,78,78,78,39,82,67,66,67]
print(df)
df.groupby("Student")["Science"].sum()

  Student  Math  Science  English  Computer  Social  Studies  Total  Hindi
0   Aarav    78       85       74        90      81      408    NaN     50
1    Diya    88       79       92        87      84      430    NaN     56
2  Ishaan    69       73       70        75      72      359    NaN     78
3   Kavya    91       89       95        93      90      458    NaN     78
4  Vivaan    76       80       78        82      77      393    NaN     78
5   Anaya    84       86       88        85      87      430    NaN     39
6  Aditya    72       68       75        70      74      359    NaN     82
7   Meera    95       94       96        97      93      475    NaN     67
8   Rohan    81       83       79        80      82      405    NaN     66
9    Siya    87       90       85        88      91      441    NaN     67

Student
Aarav     85
Aditya    68
Anaya     86
Diya      79
Ishaan    73
Kavya     89
Meera     94
Rohan     83
Siya      90
Vivaan    80
Name: Science, dtype: int64

In [17]:
df.groupby("Student")["Science"].mean()

Student
Aarav     85.0
Aditya    68.0
Anaya     86.0
Diya      79.0
Ishaan    73.0
Kavya     89.0
Meera     94.0
Rohan     83.0
Siya      90.0
Vivaan    80.0
Name: Science, dtype: float64

In [22]:
group = df.groupby("Student")["Science"].sum()
print(group["Aditya"])

68

In [19]:
df.groupby("Student")["Science"].count()

Student
Aarav     1
Aditya    1
Anaya     1
Diya      1
Ishaan    1
Kavya     1
Meera     1
Rohan     1
Siya      1
Vivaan    1
Name: Science, dtype: int64

In [26]:
%pip install openpyxl

In [29]:
import pandas as pd
df =  pd.read_excel("salesx.xlsx")
print(df)

    Order_ID  Order_Date Region Salesperson Product_Category  \
0       1001  2026-01-05  North        Aman      Electronics
1       1002  2026-01-07  South       Priya        Furniture
2       1003  2026-01-10   East       Rahul      Electronics
3       1004  2026-01-12   West        Neha       Appliances
4       1005  2026-01-15  North       Arjun        Furniture
5       1006  2026-01-18  South      Simran      Electronics
6       1007  2026-01-20   East       Karan       Appliances
7       1008  2026-01-22   West         NaN      Electronics
8       1009  2026-01-25  North       Meera        Furniture
9       1010  2026-01-28  South       Rohit      Electronics
10      1011  2026-02-02   East        Aman       Appliances
11      1012  2026-02-05   West       Priya        Furniture
12      1013  2026-02-08  North       Rahul      Electronics
13      1014  2026-02-11  South        Neha       Appliances
14      1015  2026-02-14   East       Arjun        Furniture
15      1016  2026-02-17   West      Simran      Electronics
16      1017  2026-02-20  North       Karan       Appliances
17      1018  2026-02-23  South       Meera      Electronics
18      1019  2026-02-26   East       Rohit        Furniture
19      1020  2026-02-28   West        Aman      Electronics

             Product  Units_Sold  Unit_Price  Revenue   Profit
0             Laptop           5       55000   275000  45000.0
1       Office Chair          12        3500    42000   9000.0
2             Tablet           8       18000   144000  22000.0
3          Microwave           6       12000    72000  15000.0
4               Desk           4        7000    28000   5000.0
5         Smartphone          15       25000   375000  60000.0
6       Refrigerator           3       32000    96000  18000.0
7            Monitor          10        9000    90000  14000.0
8            Cabinet           5       11000    55000      NaN
9         Headphones          20        2500    50000  12000.0
10   Air Conditioner           2       45000    90000  20000.0
11              Sofa           1       38000    38000   7000.0
12           Printer           7       15000   105000  17000.0
13    Water Purifier           9        8000    72000  13000.0
14         Bookshelf           6        6000    36000   6500.0
15            Camera           3       42000   126000  25000.0
16   Washing Machine           4       28000   112000  21000.0
17        Smartwatch          11        7000    77000  16000.0
18  Conference Table           2       25000    50000   9000.0
19            Router          14        3000    42000   8000.0

In [30]:
df = pd.read_csv("newdata.txt" , sep = ",")
print(df)

   Employee_ID    Name Department   Salary  Experience
0          101    Aman         HR  45000.0         2.0
1          102   Priya         IT  55000.0         3.0
2          103   Rahul    Finance      NaN         4.0
3          104    Neha         IT  62000.0         NaN
4          105   Arjun        NaN  48000.0         2.0
5          106  Simran  Marketing  51000.0         3.0
6          107   Karan    Finance  59000.0         NaN
7          108     NaN         HR  47000.0         1.0
8          109   Meera  Marketing      NaN         5.0
9          110   Rohit         IT  65000.0         4.0

In [31]:
print(df.isnull())

   Employee_ID   Name  Department  Salary  Experience
0        False  False       False   False       False
1        False  False       False   False       False
2        False  False       False    True       False
3        False  False       False   False        True
4        False  False        True   False       False
5        False  False       False   False       False
6        False  False       False   False        True
7        False   True       False   False       False
8        False  False       False    True       False
9        False  False       False   False       False

In [32]:
print(df.isnull().sum())

Employee_ID    0
Name           1
Department     1
Salary         2
Experience     2
dtype: int64

In [40]:
df.fillna("not available")

   Employee_ID           Name     Department         Salary     Experience
0          101           Aman             HR        45000.0            2.0
1          102          Priya             IT        55000.0            3.0
2          103          Rahul        Finance  not available            4.0
3          104           Neha             IT        62000.0  not available
4          105          Arjun  not available        48000.0            2.0
5          106         Simran      Marketing        51000.0            3.0
6          107          Karan        Finance        59000.0  not available
7          108  not available             HR        47000.0            1.0
8          109          Meera      Marketing  not available            5.0
9          110          Rohit             IT        65000.0            4.0

In [61]:
print(df.isnull().sum())
df.fillna({
    
    "Salary": 50000.0,
    "Experience" : 3,
    "Department" :"HR",
    "Name" :"not given"
})

Employee_ID    0
Name           0
Department     0
Salary         0
Experience     0
dtype: int64

   Employee_ID       Name Department   Salary  Experience
0          101       Aman         HR  45000.0         2.0
1          102      Priya         IT  55000.0         3.0
2          103      Rahul    Finance  50000.0         4.0
3          104       Neha         IT  62000.0         3.0
4          105      Arjun         HR  48000.0         2.0
5          106     Simran  Marketing  51000.0         3.0
6          107      Karan    Finance  59000.0         3.0
7          108  not given         HR  47000.0         1.0
8          109      Meera  Marketing  50000.0         5.0
9          110      Rohit         IT  65000.0         4.0

In [1]:
import pandas as pd
df = pd.read_csv("DATA.txt" , sep = ",")
print(df)

       ID           Name   Age  Gender    City    Salary
0       1  Aisha Agarwal  59.0  Female  Jaipur  105104.0
1       2    Pooja Joshi  58.0  Female  Indore   21631.0
2       3    Diya Mishra  27.0  Female     NaN  107499.0
3       4    Sneha Joshi  52.0  Female     NaN   93543.0
4       5   Pooja Mishra  42.0  Female  Bhopal   21470.0
..    ...            ...   ...     ...     ...       ...
995   996    Arjun Yadav  40.0    Male  Mumbai   37298.0
996   997    Arjun Patel   NaN    Male     NaN   68986.0
997   998    Pooja Gupta  41.0  Female  Bhopal   25696.0
998   999     Riya Joshi  39.0  Female   Patna   98158.0
999  1000   Vivaan Gupta  45.0    Male  Kanpur   97382.0

[1000 rows x 6 columns]

In [5]:
#selecting data
print(df["Name"])
print(df.loc[0])
print(df.loc[2,"Gender"])

0      Aisha Agarwal
1        Pooja Joshi
2        Diya Mishra
3        Sneha Joshi
4       Pooja Mishra
           ...
995      Arjun Yadav
996      Arjun Patel
997      Pooja Gupta
998       Riya Joshi
999     Vivaan Gupta
Name: Name, Length: 1000, dtype: str
ID                    1
Name      Aisha Agarwal
Age                59.0
Gender           Female
City             Jaipur
Salary         105104.0
Name: 0, dtype: object
Female

In [6]:
#data cleaning
print(df.isnull())
print(df.isnull().sum())

        ID   Name    Age  Gender   City  Salary
0    False  False  False   False  False   False
1    False  False  False   False  False   False
2    False  False  False   False   True   False
3    False  False  False   False   True   False
4    False  False  False   False  False   False
..     ...    ...    ...     ...    ...     ...
995  False  False  False   False  False   False
996  False  False   True   False   True   False
997  False  False  False   False  False   False
998  False  False  False   False  False   False
999  False  False  False   False  False   False

[1000 rows x 6 columns]
ID          0
Name        0
Age       100
Gender    100
City      100
Salary    100
dtype: int64

In [7]:
df.fillna(1)

       ID           Name   Age  Gender    City    Salary
0       1  Aisha Agarwal  59.0  Female  Jaipur  105104.0
1       2    Pooja Joshi  58.0  Female  Indore   21631.0
2       3    Diya Mishra  27.0  Female       1  107499.0
3       4    Sneha Joshi  52.0  Female       1   93543.0
4       5   Pooja Mishra  42.0  Female  Bhopal   21470.0
..    ...            ...   ...     ...     ...       ...
995   996    Arjun Yadav  40.0    Male  Mumbai   37298.0
996   997    Arjun Patel   1.0    Male       1   68986.0
997   998    Pooja Gupta  41.0  Female  Bhopal   25696.0
998   999     Riya Joshi  39.0  Female   Patna   98158.0
999  1000   Vivaan Gupta  45.0    Male  Kanpur   97382.0

[1000 rows x 6 columns]

In [10]:
df.fillna({
    "Age" : 20,
    "Gender" : "M/F",
    "City" : "not given",
    "Salary" : 50000.0
})

       ID           Name   Age  Gender       City    Salary
0       1  Aisha Agarwal  59.0  Female     Jaipur  105104.0
1       2    Pooja Joshi  58.0  Female     Indore   21631.0
2       3    Diya Mishra  27.0  Female  not given  107499.0
3       4    Sneha Joshi  52.0  Female  not given   93543.0
4       5   Pooja Mishra  42.0  Female     Bhopal   21470.0
..    ...            ...   ...     ...        ...       ...
995   996    Arjun Yadav  40.0    Male     Mumbai   37298.0
996   997    Arjun Patel  20.0    Male  not given   68986.0
997   998    Pooja Gupta  41.0  Female     Bhopal   25696.0
998   999     Riya Joshi  39.0  Female      Patna   98158.0
999  1000   Vivaan Gupta  45.0    Male     Kanpur   97382.0

[1000 rows x 6 columns]

In [16]:
df.dropna()
df.isnull().sum()

ID        0
Name      0
Age       0
Gender    0
City      0
Salary    0
dtype: int64

In [18]:
#filtering data
df[(df["Salary"]>50000.0) & (df["Age"]<50.0)]

       ID             Name   Age  Gender     City    Salary
9      10  Krishna Agarwal  22.0    Male   Kanpur   73430.0
11     12    Krishna Singh  37.0    Male   Indore   70349.0
15     16      Kavya Kumar  40.0  Female    Delhi  104822.0
17     18    Kavya Agarwal  22.0  Female   Mumbai   99743.0
37     38      Sneha Yadav  45.0  Female   Jaipur   75327.0
..    ...              ...   ...     ...      ...       ...
985   986        Sai Verma  28.0    Male  Lucknow   59586.0
988   989     Sneha Mishra  18.0  Female     Pune   64008.0
989   990      Pooja Gupta  21.0  Female   Indore   74117.0
998   999       Riya Joshi  39.0  Female    Patna   98158.0
999  1000     Vivaan Gupta  45.0    Male   Kanpur   97382.0

[352 rows x 6 columns]

In [20]:
#add columns 
df["Locality"] = "Urban"
print(df)

       ID           Name   Age  Gender    City    Salary Locality
0       1  Aisha Agarwal  59.0  Female  Jaipur  105104.0    Urban
1       2    Pooja Joshi  58.0  Female  Indore   21631.0    Urban
4       5   Pooja Mishra  42.0  Female  Bhopal   21470.0    Urban
5       6   Vivaan Joshi  60.0    Male   Patna   58496.0    Urban
6       7   Meera Mishra  52.0  Female   Noida   88180.0    Urban
..    ...            ...   ...     ...     ...       ...      ...
994   995    Neha Mishra  50.0  Female   Noida  105665.0    Urban
995   996    Arjun Yadav  40.0    Male  Mumbai   37298.0    Urban
997   998    Pooja Gupta  41.0  Female  Bhopal   25696.0    Urban
998   999     Riya Joshi  39.0  Female   Patna   98158.0    Urban
999  1000   Vivaan Gupta  45.0    Male  Kanpur   97382.0    Urban

[658 rows x 7 columns]

In [22]:
#groupby
df.groupby("Name")["Salary"].sum()

Name
Aarav Agarwal    126551.0
Aarav Gupta       74161.0
Aarav Joshi      172472.0
Aarav Kumar      260830.0
Aarav Mishra      68685.0
                   ...
Vivaan Kumar     335650.0
Vivaan Mishra     54085.0
Vivaan Patel     336659.0
Vivaan Sharma    214707.0
Vivaan Verma     210102.0
Name: Salary, Length: 194, dtype: float64

In [23]:
df.groupby("Name")["Salary"].max()

Name
Aarav Agarwal     68279.0
Aarav Gupta       53576.0
Aarav Joshi      107791.0
Aarav Kumar      109411.0
Aarav Mishra      68685.0
                   ...
Vivaan Kumar     112206.0
Vivaan Mishra     54085.0
Vivaan Patel      85929.0
Vivaan Sharma     95816.0
Vivaan Verma      95802.0
Name: Salary, Length: 194, dtype: float64

In [24]:
df.groupby("Name")["Salary"].count()

Name
Aarav Agarwal    2
Aarav Gupta      2
Aarav Joshi      2
Aarav Kumar      3
Aarav Mishra     1
                ..
Vivaan Kumar     5
Vivaan Mishra    1
Vivaan Patel     6
Vivaan Sharma    3
Vivaan Verma     4
Name: Salary, Length: 194, dtype: int64